In [1]:
import os
import zipfile
import numpy as np
import tensorflow as tf
from tensorboard.plugins import projector

In [2]:
import tools.processing as pre
import tools.embedding as emb

text = pre.get_text("data/cleaned-rap-lyrics/final_2_pac_rakim_kid_cudi.txt")

vocab = pre.Vocabulary(text)
index2word_map = vocab.index2word_map
word2index_map = vocab._dict
vocabulary_size = len(index2word_map)

# create embedding for words
word_embedding_matrix = emb.get_embedding_matrix(word2index_map, vocabulary_size)
print(word_embedding_matrix)

[[ 0.0848636   0.04045071  0.07530911 ... -0.00327249 -0.03926468
   0.00752516]
 [ 0.00153569  0.12661901  0.09518377 ...  0.01355811  0.01934354
  -0.0286953 ]
 [ 0.00486193  0.14006345  0.08130748 ...  0.00033818  0.03776005
  -0.02884221]
 ...
 [ 0.09170229 -0.04923349 -0.01742387 ...  0.08653232 -0.0250071
  -0.02735833]
 [ 0.0044884   0.10705608  0.00423622 ...  0.13541482 -0.01943643
  -0.10687874]
 [ 0.03727657 -0.02300504  0.08994251 ...  0.02934486 -0.05716072
  -0.04860425]]


In [4]:
len(word_embedding_matrix)

8471

In [5]:
phonems = pre.get_text("data/phonem-rap-lyrics/phonem_all.txt")

vocab_phonem = pre.Vocabulary(phonems)
index2phonem_map = vocab_phonem.index2word_map
phonem2index_map = vocab_phonem._dict
vocabulary_size_phonem = len(index2phonem_map)

# create embedding for phonems
phonem_embedding_matrix = emb.get_phonem_embedding_matrix(phonem2index_map, vocabulary_size_phonem)
print(phonem_embedding_matrix)

[[-0.83106965 -0.53812933  0.14049865]
 [-0.57452571 -0.45615974  0.67958683]
 [-0.85238743 -0.27057332 -0.4474659 ]
 [-0.89024484 -0.43297064  0.14142321]
 [-0.889552   -0.42086163  0.17768735]
 [-0.84767091  0.20958452 -0.48736873]
 [-0.80071777 -0.59023607 -0.10233522]
 [-0.8041234  -0.43067229  0.40976447]
 [-0.85063279 -0.25427106 -0.46018487]
 [-0.83106846 -0.49368501 -0.25612572]
 [-0.77628517 -0.57696062 -0.25396407]
 [-0.85525501  0.34369221  0.38783291]
 [-0.72286534 -0.66972053  0.17011791]
 [-0.90681714  0.07853168 -0.41414431]
 [-0.84486431 -0.38346329 -0.37304166]
 [-0.73923445 -0.57153291 -0.35620561]
 [-0.94168699  0.08752931  0.32490653]
 [ 0.91624618 -0.1400506  -0.37533814]
 [-0.88760549 -0.45781818 -0.05058585]
 [-0.95192575  0.20271704 -0.22965866]
 [-0.88998002  0.08347418 -0.44829413]
 [-0.1288805  -0.28575739 -0.94959605]
 [-0.87844598 -0.46678743 -0.10218589]
 [-0.99973291  0.0226963   0.00435353]
 [-0.92469871  0.07278427  0.37367749]
 [-0.92872733  0.10954829

In [6]:
len(phonem_embedding_matrix)

85